/**
 * Leave Quota Availability
 * Api to know to leave availablity for a particular block.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ranjithkumar.kodangil@boeing.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ErrorModel {
    code: number;

    message: string;

}
